name: bilibilitoolpro
services:
  bilibilitoolpro:
    environment:
      Ray_DailyTaskConfig__AutoChargeUpId: "-1"
      Ray_DailyTaskConfig__Cron: 0 15 * * *
      Ray_LiveLotteryTaskConfig__Cron: 0 22 * * *
      Ray_UnfollowBatchedTaskConfig__Cron: 0 6 1 * *
      Ray_VipBigPointConfig__Cron: 7 1 * * *
    image: ghcr.io/raywangqvq/bilibili_tool_pro:latest
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/bilibilitoolpro/cookies.json
        target: /app/cookies.json
      - type: bind
        source: /DATA/AppData/bilibilitoolpro/Logs
        target: /app/Logs
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: Cp0204
  category: WEB
  description:
    en_us:
    zh_cn: BiliBiliTool 是一个自动执行任务的工具，当我们忘记做某项任务时，它会像一个贴心小助手，按照我们预先吩咐它的命令，在指定频率、时间范围内帮助我们完成计划的任务。
  developer: raywangqvq
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/BiliBiliToolPro/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/BiliBiliToolPro/screenshot-1.png
  tagline:
    en_us:
    zh_cn: 自动执行任务的工具
  thumbnail: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/BiliBiliToolPro/thumbnail.png
  tips:
    before_install:
      en_us:
      zh_cn: 安装前先建立 `/DATA/AppData/bilibilitoolpro/cookies.json` 文件，内容 `{}`
        详读： https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docker/README.md
  main: bilibilitoolpro
  scheme: http
  title:
    en_us: BiliBiliToolPro
