name: immich

services:
  database:
    container_name: immich-postgres
    environment:
      - POSTGRES_DB=immich
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    hostname: immich-postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/immich/pgdata
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    networks:
      - immich
    privileged: false

  immich-machine-learning:
    container_name: immich-machine-learning
    environment:
      - DB_DATABASE_NAME=immich
      - DB_HOSTNAME=immich-postgres
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      # - HTTP_PROXY=http://172.17.0.1:10809
      # - HTTPS_PROXY=http://172.17.0.1:10809
      - REDIS_HOSTNAME=immich-redis
    hostname: immich-machine-learning
    image: altran1502/immich-machine-learning:release
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/immich/model-cache
        target: /cache
        bind:
          create_host_path: true
    networks:
      - immich
    privileged: false

  immich-microservices:
    command:
      - start.sh
      - microservices
    container_name: immich-microservices
    depends_on:
      database:
        condition: service_started
        required: true
      redis:
        condition: service_started
        required: true
    environment:
      - DB_DATABASE_NAME=immich
      - DB_HOSTNAME=immich-postgres
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - REDIS_HOSTNAME=immich-redis
    hostname: immich-microservices
    image: altran1502/immich-server:release
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Gallery/immich
        target: /usr/src/app/upload
        bind:
          create_host_path: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
    networks:
      - immich
    privileged: false

  immich-server:
    command:
      - start.sh
      - immich
    container_name: immich-server
    depends_on:
      database:
        condition: service_started
        required: true
      redis:
        condition: service_started
        required: true
    environment:
      - DB_DATABASE_NAME=immich
      - DB_HOSTNAME=immich-postgres
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - REDIS_HOSTNAME=immich-redis
    hostname: immich-server
    image: altran1502/immich-server:release
    ports:
      - mode: ingress
        target: 3001
        published: "2283"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Gallery/immich
        target: /usr/src/app/upload
        bind:
          create_host_path: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
    networks:
      - immich
    privileged: false

  redis:
    container_name: immich-redis
    hostname: immich-redis
    image: redis:6.2-alpine
    restart: unless-stopped
    networks:
      - immich
    privileged: false

networks:
  immich:
    name: immich

x-casaos:
  architectures:
    - amd64
    - arm64
  main: immich-server
  store_app_id: immich
  category: Gallery
  author: Cp0204
  developer: Alex
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/immich/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/immich/screenshot-1.png
  thumbnail: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/immich/thumbnail.png
  description:
    en_us: 'Alex is a software engineer who, along with his wife, faced a common problem after the birth of their newborn: they didn''t want to pay for a backup application anymore. So, he decided to develop an alternative focused on backing up photos and videos. This application prioritizes privacy protection and offers user-friendly access to photos and videos. Alex aims to give back to the open-source community through this project.'
    zh_cn: Alex 是一位软件工程师，他与妻子在新生儿出生后面对一个共同问题：不想再为付费备份应用买单了。于是，他决定开发一个替代品，专注于照片和视频备份。这款应用注重隐私保护，方便用户查看照片和视频，操作简单易用。Alex 希望通过这个项目回馈开源社区。
  tagline:
    en_us: High performance self-hosted photo and video backup solution
    zh_cn: 高性能的自托管照片和视频备份方案
  title:
    en_us: immich
  tips:
    before_install:
      en_us: |
        ⚠️ The project is under very active development.
        ⚠️ Expect bugs and breaking changes.
        ⚠️ Do not use the app as the only way to store your photos and videos.
        ⚠️ Always follow 3-2-1 backup plan for your precious photos and videos!
      zh_cn: |
        ⚠️ 本项目正在 非常活跃 地开发中。
        ⚠️ 可能存在 bug 或者随时有重大变更。
        ⚠️ 不要把本软件作为您存储照片或视频的唯一方式。
        ⚠️ 为了您宝贵的照片与视频，请始终遵守 3-2-1 备份方案！
  port_map: '2283'
  scheme: http
  index: /
