name: rustdesk-server
services:
  hbbr:
    command:
      - hbbr
    container_name: rustdesk-server-hbbr
    image: rustdesk/rustdesk-server:latest
    restart: unless-stopped
    volumes:
      - /DATA/AppData/rustdesk-server/hbbr:/root
    network_mode: bridge
    ports:
      - "21117:21117/tcp"
      - "21119:21119/tcp"
    privileged: false

  hbbs:
    command:
      - hbbs
    container_name: rustdesk-server-hbbs
    depends_on:
      hbbr:
        condition: service_started
        required: true
    image: rustdesk/rustdesk-server:latest
    restart: unless-stopped
    volumes:
      - /DATA/AppData/rustdesk-server/hbbs:/root
    network_mode: bridge
    ports:
      - "21115:21115/tcp"
      - "21118:21118/tcp"
      - "21116:21116/tcp"
      - "21116:21116/udp"
    privileged: false

  rustdesk-server-api:
    container_name: rustdesk-server-api
    environment:
      - CSRF_TRUSTED_ORIGINS=http://yourdomian.com:21114
      - HOST=0.0.0.0
      - TZ=Asia/Shanghai
    image: ghcr.io/cp0204/rustdesk-api-server:master
    ports:
      - "21114:21114/tcp"
    restart: unless-stopped
    volumes:
      - /DATA/AppData/rustdesk-server/api/db:/rustdesk-api-server/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    privileged: false

x-casaos:
  author: Cp0204
  category: self
  description:
    en_us: rustdesk self-built relay server, integrating rustdesk-server and kingmo888's rustdesk-server-api service
    zh_cn: rustdesk自建中转服务器，集合rustdesk-server与kingmo888的rustdesk-server-api服务
  icon: https://avatars.githubusercontent.com/u/71636191
  index: /
  port_map: "21114"
  scheme: http
  store_app_id: rustdesk-server
  title:
    custom: rustdesk-server
