name: Create Release

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Filter and Create Release
        id: create_release
        run: |
          find . -type f \( -name "*.json" -o -name "*.yml" \) -exec zip AppStore.zip {} +
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete latest tag and release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload New Release
        uses: softprops/action-gh-release@v1
        with:
          files: AppStore.zip
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
